apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 557.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '5'
    run.googleapis.com/operation-id: 41fa4eef-6855-48a2-be81-60100dd722b1
    run.googleapis.com/urls: '["https://voice-bot-820513756722.us-central1.run.app","https://voice-bot-mcdqao6eba-uc.a.run.app"]'
    serving.knative.dev/creator: 820513756722-compute@developer.gserviceaccount.com
    serving.knative.dev/lastModifier: 820513756722-compute@developer.gserviceaccount.com
  creationTimestamp: '2026-02-17T20:26:03.867160Z'
  generation: 25
  labels:
    cloud.googleapis.com/location: us-central1
  name: voice-bot
  namespace: '820513756722'
  resourceVersion: AAZLKX9N+9Y
  selfLink: /apis/serving.knative.dev/v1/namespaces/820513756722/services/voice-bot
  uid: eb96efa3-9563-4274-987c-25d2a490a14c
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 557.0.0
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: pykqjoidav
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 320
      containers:
      - env:
        - name: LIVEKIT_URL
          value: wss://voice-4bn0hc02.livekit.cloud
        - name: LIVEKIT_API_KEY
          value: ''
        - name: LIVEKIT_API_SECRET
          value: ''
        - name: GOOGLE_CLOUD_PROJECT
          value: gen-lang-client-0133143947
        - name: GOOGLE_CLOUD_LOCATION
          value: us-central1
        - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
          value: '{}'
        - name: GEMINI_API_KEY
          value: ''
        image: gcr.io/gen-lang-client-0133143947/voice-backend:v7-1353f0b491ab2a8230d58f0b1e980dde7760bbb6
        name: voice-backend-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 820513756722-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://voice-bot-mcdqao6eba-uc.a.run.app
  conditions:
  - lastTransitionTime: '2026-02-19T08:57:41.823446Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-02-19T08:55:18.593114Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-02-19T08:57:41.778343Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: voice-bot-00025-btv
  latestReadyRevisionName: voice-bot-00025-btv
  observedGeneration: 25
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: voice-bot-00025-btv
  url: https://voice-bot-mcdqao6eba-uc.a.run.app
